# -*- mode: shell-script -*-
# -*- coding: utf-8 -*-
umask 022

#zsh
autoload -U colors
colors
autoload -U compinit
compinit
setopt correct
setopt beep

setopt list_types
setopt auto_list
setopt auto_menu
setopt magic_equal_subst
setopt auto_cd
setopt auto_param_keys
setopt pushd_ignore_dups
setopt auto_pushd

watch="all"
log

local GREEN=$'%{\e[1;32m%}'
local YELLOW=$'%{\e[1;33m%}'
local BLUE=$'%{\e[1;34m%}'
local LIGHT_BLUE=$'%{\e[1;36m%}'
local DEFAULT=$'%{\e[1;0m%}'
if [ "$TERM" = "emacs" ] ; then
    PROMPT="${LIGHT_BLUE}Yes, Master${DEFAULT}@${GREEN}${HOST}?${DEFAULT} [${BLUE}%/${DEFAULT}]%% "
else
    PROMPT="${LIGHT_BLUE}Yes, Master${DEFAULT}@${GREEN}${HOST}?${DEFAULT} [${BLUE}%/${DEFAULT}]%% "
fi

PROMPT2="%_%% "

SPROMPT="%r? べ, 別にあんたのために修正したんじゃないんだからね! [n,y,a,e]:"

HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt hist_ignore_dups     # ignore duplication command history list
setopt share_history        # share command history data
bindkey -e

export MAKE_MODE=unix

export PATH=./:/bin:/usr/bin:/usr/local/bin:/sbin
export LD_LIBRARY_PATH=/lib:/usr/bin:/usr/local/lib
export PATH=$PATH:/usr/lib/lapack

#export LANG=C

#alias
#alias ls='\ls -CF --color=auto --show-control-chars'
alias ls='\ls -GF'
alias cp='cp -v'
alias mv='mv -v'
alias grep='grep --color=auto'

#ssh-agent
echo -n "ssh-agent: "
source ~/.ssh-agent-info
ssh-add -l >&/dev/null
if [ $? = 2 ] ; then
    echo -n "ssh-agent: restart...."
    ssh-agent >~/.ssh-agent-info
    source ~/.ssh-agent-info
fi
if ssh-add -l >&/dev/null ; then
    echo "ssh-agent: Identity is already stored."
else
    ssh-add
fi

# load each architecture settings ...
OS=`uname`
if [ "$OS" = "CYGWIN_NT-5.1" -o "$OS" = "CYGWIN_NT-6.0" ] ; then
    if [ ! -e $HOME/.zshrc.cygwin ]; then
        echo loading cygwin setup file ...
        source $HOME/.zshrc.cygwin
    fi
elif [ "$OS" = "Linux" ] ; then
    if [ ! -e $HOME/.zshrc.linux ]; then
        echo loading linux setup file ...
        source $HOME/.zshrc.linux
    fi
elif [ "$OS" = "Darwin" ] ; then
    if [ ! -e $HOME/.zshrc.darwin ]; then
        echo loading darwin setup file ...
        source $HOME/.zshrc.darwin
    fi
fi

alias slime="emacs -f slime"

# for emacs-settings
export PATH=$PATH:$HOME/gprog/emacs-settings
# source ~/.zshrc.ros
# VERSIONER_PYTHON_PREFER_32_BIT=yes


alias rm='trash-put -v'

